# Generated by Django 2.2.1 on 2020-04-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(max_length=25),
        ),
    ]
