# Generated by Django 2.2.1 on 2020-04-24 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('des', models.TextField(max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('create', models.TimeField(auto_now_add=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('update', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete='CASCADE', related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
